<?php
$watches = array (
  'On-Hold' => 
  array (
    0 => 
    array (
      'id' => '60014',
      'title' => 'Perfect Secret Love: The Bad New Wife is a Little Sweet',
      'availvol' => '-1',
      'availchp' => '95.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '548.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '89241',
      'title' => 'Black Tech Internet Cafe System',
      'availvol' => '-1',
      'availchp' => '129.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '270.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '42461',
      'title' => 'Cultivation Chat Group',
      'availvol' => '-1',
      'availchp' => '1107.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '481.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '63739',
      'title' => 'Diavazo Logs: Motivating a Bookworm Protagonist',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '60.0',
      'frg' => '-1',
    ),
    4 => 
    array (
      'id' => '48692',
      'title' => 'Evil Emperor&#39;s Wild Consort',
      'availvol' => '-1',
      'availchp' => '292.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1013.0',
      'frg' => '-1',
    ),
    5 => 
    array (
      'id' => '58887',
      'title' => 'Fishing the Myriad Heavens',
      'availvol' => '-1',
      'availchp' => '638.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '641.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '50175',
      'title' => 'Forty Millenniums of Cultivation',
      'availvol' => '-1',
      'availchp' => '336.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1045.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '43213',
      'title' => 'Genius Doctor: Black Belly Miss',
      'availvol' => '-1',
      'availchp' => '1977.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '2152.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '50416',
      'title' => 'Ghost Emperor Wild Wife: Dandy Eldest Miss',
      'availvol' => '-1',
      'availchp' => '373.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '481.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '50236',
      'title' => 'Godly Model Creator',
      'availvol' => '-1',
      'availchp' => '609.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '764.0',
      'frg' => '-1',
    ),
    10 => 
    array (
      'id' => '56109',
      'title' => 'Insanely Pampered Wife: Divine Doctor Fifth Young Miss',
      'availvol' => '-1',
      'availchp' => '500.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '377.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '33427',
      'title' => 'Lord Xue Ying',
      'availvol' => '14.0',
      'availchp' => '19.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '562.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '104263',
      'title' => 'Master of Time',
      'availvol' => '-1',
      'availchp' => '110.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '138.0',
      'frg' => '-1',
    ),
    13 => 
    array (
      'id' => '57756',
      'title' => 'Mesmerizing Ghost Doctor',
      'availvol' => '-1',
      'availchp' => '278.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '399.0',
      'frg' => '-1',
    ),
    14 => 
    array (
      'id' => '59571',
      'title' => 'Monster Paradise',
      'availvol' => '-1',
      'availchp' => '760.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '826.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '61126',
      'title' => 'Mr. CEO, Spoil me 100 Percent!',
      'availvol' => '-1',
      'availchp' => '100.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '369.0',
      'frg' => '-1',
    ),
    16 => 
    array (
      'id' => '61312',
      'title' => 'Mystical Journey',
      'availvol' => '-1',
      'availchp' => '116.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '512.0',
      'frg' => '-1',
    ),
    17 => 
    array (
      'id' => '34411',
      'title' => 'Night Ranger',
      'availvol' => '-1',
      'availchp' => '455.0',
      'availfrag' => '0.0',
      'vol' => '1.0',
      'chp' => '496.0',
      'frg' => '-1',
    ),
    18 => 
    array (
      'id' => '49310',
      'title' => 'Paradise of Demons and Gods',
      'availvol' => '-1',
      'availchp' => '427.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '525.0',
      'frg' => '-1',
    ),
    19 => 
    array (
      'id' => '48694',
      'title' => 'Village Girl as Family Head : picked up a general for farming',
      'availvol' => '-1',
      'availchp' => '114.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '66.0',
      'frg' => '-1',
    ),
    20 => 
    array (
      'id' => '57270',
      'title' => 'Prodigiously Amazing Weaponsmith',
      'availvol' => '-1',
      'availchp' => '56.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '685.0',
      'frg' => '-1',
    ),
    21 => 
    array (
      'id' => '71456',
      'title' => 'Soul of Searing Steel',
      'availvol' => '-1',
      'availchp' => '59.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '897.0',
      'frg' => '-1',
    ),
    22 => 
    array (
      'id' => '83993',
      'title' => 'Spending My Retirement In A Game',
      'availvol' => '-1',
      'availchp' => '84.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '335.0',
      'frg' => '-1',
    ),
    23 => 
    array (
      'id' => '58039',
      'title' => 'The Anarchic Consort',
      'availvol' => '-1',
      'availchp' => '213.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '274.0',
      'frg' => '-1',
    ),
    24 => 
    array (
      'id' => '34998',
      'title' => 'The Avalon Of Five Elements',
      'availvol' => '-1',
      'availchp' => '691.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '332.0',
      'frg' => '-1',
    ),
    25 => 
    array (
      'id' => '67117',
      'title' => 'The Daily Life of the Immortal King',
      'availvol' => '-1',
      'availchp' => '898.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '147.0',
      'frg' => '-1',
    ),
    26 => 
    array (
      'id' => '65894',
      'title' => 'The Empress&#39;s Gigolo',
      'availvol' => '-1',
      'availchp' => '113.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '950.0',
      'frg' => '-1',
    ),
    27 => 
    array (
      'id' => '34481',
      'title' => 'The Magus Era',
      'availvol' => '-1',
      'availchp' => '741.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '793.0',
      'frg' => '-1',
    ),
    28 => 
    array (
      'id' => '60981',
      'title' => 'Venerated Venomous Consort',
      'availvol' => '-1',
      'availchp' => '680.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '899.0',
      'frg' => '-1',
    ),
    29 => 
    array (
      'id' => '58288',
      'title' => 'War Sovereign Soaring The Heavens',
      'availvol' => '-1',
      'availchp' => '1130.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '879.0',
      'frg' => '-1',
    ),
    30 => 
    array (
      'id' => '35887',
      'title' => 'Wu Dong Qian Kun',
      'availvol' => '-1',
      'availchp' => '1311.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1274.0',
      'frg' => '-1',
    ),
  ),
  'Plan To Read' => 
  array (
    0 => 
    array (
      'id' => '32652',
      'title' => 'Dragon&#39;s Soul',
      'availvol' => '-1',
      'availchp' => '273.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    1 => 
    array (
      'id' => '34120',
      'title' => 'Goddess Grant me a Girlfriend',
      'availvol' => '1.0',
      'availchp' => '10.0',
      'availfrag' => '0.0',
      'vol' => '2.0',
      'chp' => '0.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '3209',
      'title' => 'Harem King',
      'availvol' => '-1',
      'availchp' => '5.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    3 => 
    array (
      'id' => '3169',
      'title' => 'Harem Reaper',
      'availvol' => '2.0',
      'availchp' => '6.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    4 => 
    array (
      'id' => '59317',
      'title' => 'I Was Made the Disciple of a Yandere Girl, But',
      'availvol' => '-1',
      'availchp' => '45.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    5 => 
    array (
      'id' => '1025',
      'title' => 'Kono Bushitsu wa Kitaku Shinai Bu ga Senkyo Shimashita.',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    6 => 
    array (
      'id' => '60944',
      'title' => 'Martial Arts Master',
      'availvol' => '-1',
      'availchp' => '450.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '3394',
      'title' => 'Slavemancer',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    8 => 
    array (
      'id' => '2766',
      'title' => 'The Fragile Monster Lord',
      'availvol' => '-1',
      'availchp' => '175.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    9 => 
    array (
      'id' => '34956',
      'title' => 'The Liar Face Demon (Legendary Wizard Saint)',
      'availvol' => '-1',
      'availchp' => '32.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    10 => 
    array (
      'id' => '35308',
      'title' => 'They came by the dozen (Dropped)',
      'availvol' => '-1',
      'availchp' => '4.0',
      'availfrag' => '3.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    11 => 
    array (
      'id' => '57171',
      'title' => 'The Sage Who Transcended Samsara',
      'availvol' => '1.0',
      'availchp' => '1.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
  ),
  'Qidian' => 
  array (
    0 => 
    array (
      'id' => '110418',
      'title' => 'Abe the Wizard',
      'availvol' => '-1',
      'availchp' => '48.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '519.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '47429',
      'title' => 'Abyss Domination',
      'availvol' => '2.0',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '2.0',
      'chp' => '500.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '84068',
      'title' => 'Another World&#39;s Versatile Crafting Master',
      'availvol' => '-1',
      'availchp' => '94.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '729.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '34567',
      'title' => 'Badge in Azure',
      'availvol' => '-1',
      'availchp' => '501.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1320.0',
      'frg' => '-1',
    ),
    4 => 
    array (
      'id' => '115752',
      'title' => 'Building The Ultimate Fantasy',
      'availvol' => '-1',
      'availchp' => '106.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '264.0',
      'frg' => '-1',
    ),
    5 => 
    array (
      'id' => '63420',
      'title' => 'Carefree Path of Dreams',
      'availvol' => '-1',
      'availchp' => '112.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1180.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '56289',
      'title' => 'Reverend Insanity',
      'availvol' => '1.0',
      'availchp' => '1.0',
      'availfrag' => '0.0',
      'vol' => '1.0',
      'chp' => '1911.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '109803',
      'title' => 'Demons Beside You',
      'availvol' => '-1',
      'availchp' => '74.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '687.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '69837',
      'title' => 'End of the Magic Era',
      'availvol' => '-1',
      'availchp' => '100.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1191.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '110446',
      'title' => 'Eternal Sacred King',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '448.0',
      'frg' => '-1',
    ),
    10 => 
    array (
      'id' => '107434',
      'title' => 'Fatal Shot',
      'availvol' => '-1',
      'availchp' => '100.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '422.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '109601',
      'title' => 'I Don&#39;t Want To Defy The Heavens',
      'availvol' => '-1',
      'availchp' => '103.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '448.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '57679',
      'title' => 'I Have a Mansion in the Post-apocalyptic World',
      'availvol' => '-1',
      'availchp' => '637.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1151.0',
      'frg' => '-1',
    ),
    13 => 
    array (
      'id' => '115268',
      'title' => 'I Have Countless Legendary Swords!',
      'availvol' => '-1',
      'availchp' => '1.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '310.0',
      'frg' => '-1',
    ),
    14 => 
    array (
      'id' => '111089',
      'title' => 'Let Me Game in Peace',
      'availvol' => '-1',
      'availchp' => '42.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '458.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '64956',
      'title' => 'Lord of the Mysteries',
      'availvol' => '-1',
      'availchp' => '131.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1401.0',
      'frg' => '-1',
    ),
    16 => 
    array (
      'id' => '115777',
      'title' => 'Mages Are Too OP',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '292.0',
      'frg' => '-1',
    ),
    17 => 
    array (
      'id' => '115059',
      'title' => 'Master of the End Times',
      'availvol' => '-1',
      'availchp' => '38.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '308.0',
      'frg' => '-1',
    ),
    18 => 
    array (
      'id' => '70305',
      'title' => 'Nano Machine',
      'availvol' => '-1',
      'availchp' => '34.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '330.0',
      'frg' => '-1',
    ),
    19 => 
    array (
      'id' => '70346',
      'title' => 'Nano Machine',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '330.0',
      'frg' => '-1',
    ),
    20 => 
    array (
      'id' => '110396',
      'title' => 'Nightmare&#39;s Call',
      'availvol' => '-1',
      'availchp' => '80.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '586.0',
      'frg' => '-1',
    ),
    21 => 
    array (
      'id' => '45087',
      'title' => 'Rebirth of the Godly Prodigal',
      'availvol' => '-1',
      'availchp' => '88.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1315.0',
      'frg' => '-1',
    ),
    22 => 
    array (
      'id' => '62448',
      'title' => 'Summoning the Holy Sword',
      'availvol' => '-1',
      'availchp' => '87.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1081.0',
      'frg' => '-1',
    ),
    23 => 
    array (
      'id' => '98914',
      'title' => 'Warlock Apprentice',
      'availvol' => '1.0',
      'availchp' => '74.0',
      'availfrag' => '0.0',
      'vol' => '1.0',
      'chp' => '832.0',
      'frg' => '-1',
    ),
    24 => 
    array (
      'id' => '61174',
      'title' => 'Super Gene',
      'availvol' => '-1',
      'availchp' => '498.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '2451.0',
      'frg' => '-1',
    ),
    25 => 
    array (
      'id' => '109194',
      'title' => 'The First Order',
      'availvol' => '-1',
      'availchp' => '110.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '518.0',
      'frg' => '-1',
    ),
    26 => 
    array (
      'id' => '76626',
      'title' => 'The Legendary Mechanic',
      'availvol' => '-1',
      'availchp' => '151.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '966.0',
      'frg' => '-1',
    ),
    27 => 
    array (
      'id' => '75703',
      'title' => 'Zombie Sister Strategy',
      'availvol' => '-1',
      'availchp' => '76.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1269.0',
      'frg' => '-1',
    ),
  ),
  'Qidian Completed' => 
  array (
    0 => 
    array (
      'id' => '82866',
      'title' => 'A Wizard&#39;s Secret',
      'availvol' => '-1',
      'availchp' => '128.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1063.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '69742',
      'title' => 'Adopted Soldier',
      'availvol' => '-1',
      'availchp' => '125.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '410.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '59537',
      'title' => 'Assassin&#39;s Chronicle',
      'availvol' => '-1',
      'availchp' => '580.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '580.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '53461',
      'title' => 'Castle of Black Iron',
      'availvol' => '3.0',
      'availchp' => '9.0',
      'availfrag' => '0.0',
      'vol' => '3.0',
      'chp' => '2015.0',
      'frg' => '-1',
    ),
    4 => 
    array (
      'id' => '53175',
      'title' => 'Advent of the Archmage',
      'availvol' => '-1',
      'availchp' => '381.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '726.0',
      'frg' => '-1',
    ),
    5 => 
    array (
      'id' => '42052',
      'title' => 'Galactic Dark Net',
      'availvol' => '-1',
      'availchp' => '470.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '470.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '35069',
      'title' => 'God Of Slaughter',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1618.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '90644',
      'title' => 'I Found A Planet',
      'availvol' => '-1',
      'availchp' => '117.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '493.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '96278',
      'title' => 'Legend of the Mythological Genes',
      'availvol' => '-1',
      'availchp' => '370.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '520.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '54285',
      'title' => 'Library of Heaven&#39;s Path',
      'availvol' => '-1',
      'availchp' => '1851.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '2268.0',
      'frg' => '-1',
    ),
    10 => 
    array (
      'id' => '66904',
      'title' => 'My Master Disconnected Yet Again',
      'availvol' => '-1',
      'availchp' => '31.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '704.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '62409',
      'title' => 'Omnipotent Sage',
      'availvol' => '-1',
      'availchp' => '709.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '897.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '34070',
      'title' => 'Otherworldly Evil Monarch',
      'availvol' => '2.0',
      'availchp' => '565.0',
      'availfrag' => '-1',
      'vol' => '2.0',
      'chp' => '1277.0',
      'frg' => '-1',
    ),
    13 => 
    array (
      'id' => '43524',
      'title' => 'Release that Witch',
      'availvol' => '-1',
      'availchp' => '1357.0',
      'availfrag' => '1.0',
      'vol' => '-1',
      'chp' => '1498.0',
      'frg' => '-1',
    ),
    14 => 
    array (
      'id' => '63150',
      'title' => 'Silent Crown',
      'availvol' => '-1',
      'availchp' => '724.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '812.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '58134',
      'title' => 'The Strongest Gene',
      'availvol' => '-1',
      'availchp' => '122.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '880.0',
      'frg' => '-1',
    ),
    16 => 
    array (
      'id' => '57067',
      'title' => 'The Wizard World',
      'availvol' => '-1',
      'availchp' => '595.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '646.0',
      'frg' => '-1',
    ),
    17 => 
    array (
      'id' => '34789',
      'title' => 'Throne of Magical Arcana',
      'availvol' => '-1',
      'availchp' => '73.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '910.0',
      'frg' => '-1',
    ),
    18 => 
    array (
      'id' => '33500',
      'title' => 'Warlock of the Magus World',
      'availvol' => '-1',
      'availchp' => '1200.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1200.0',
      'frg' => '-1',
    ),
  ),
  'Qidian On-Hold' => 
  array (
    0 => 
    array (
      'id' => '57678',
      'title' => 'A Sorcerer&#39;s Journey',
      'availvol' => '-1',
      'availchp' => '513.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '643.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '109593',
      'title' => 'Dark Moon Era',
      'availvol' => '-1',
      'availchp' => '102.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '433.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '62924',
      'title' => 'Godly Empress Doctor',
      'availvol' => '-1',
      'availchp' => '278.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '278.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '110110',
      'title' => 'I Am A Legendary BOSS',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '353.0',
      'frg' => '-1',
    ),
    4 => 
    array (
      'id' => '112909',
      'title' => 'Kalar&#39;s continent',
      'availvol' => '-1',
      'availchp' => '29.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '56.0',
      'frg' => '-1',
    ),
    5 => 
    array (
      'id' => '110835',
      'title' => 'Mini World Of Endless Fun Awaits',
      'availvol' => '-1',
      'availchp' => '29.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '262.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '110698',
      'title' => 'Nine Astra Skies',
      'availvol' => '-1',
      'availchp' => '44.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '381.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '60390',
      'title' => 'Reincarnation Of The Strongest Sword God',
      'availvol' => '-1',
      'availchp' => '781.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '2694.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '62143',
      'title' => 'Shadow Hack',
      'availvol' => '-1',
      'availchp' => '395.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '989.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '107499',
      'title' => 'Sword of Dawnbreaker',
      'availvol' => '-1',
      'availchp' => '38.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '226.0',
      'frg' => '-1',
    ),
    10 => 
    array (
      'id' => '50246',
      'title' => 'The City of Terror',
      'availvol' => '-1',
      'availchp' => '301.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '642.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '85593',
      'title' => 'The Great Worm Lich',
      'availvol' => '-1',
      'availchp' => '432.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '677.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '109439',
      'title' => 'The Man from Hell',
      'availvol' => '-1',
      'availchp' => '92.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '419.0',
      'frg' => '-1',
    ),
    13 => 
    array (
      'id' => '108991',
      'title' => 'Warlord of Chaos',
      'availvol' => '-1',
      'availchp' => '166.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '282.0',
      'frg' => '-1',
    ),
    14 => 
    array (
      'id' => '59558',
      'title' => 'Way of the Devil',
      'availvol' => '-1',
      'availchp' => '284.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '772.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '112910',
      'title' => 'Who said a mosquito can&#39;t cultivate?',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '43.0',
      'frg' => '-1',
    ),
  ),
  'Qidian Original' => 
  array (
    0 => 
    array (
      'id' => '103958',
      'title' => 'Birth of the Demonic Sword',
      'availvol' => '-1',
      'availchp' => '21.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '918.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '2768',
      'title' => 'Chrysalis',
      'availvol' => '-1',
      'availchp' => '587.0',
      'availfrag' => '2.0',
      'vol' => '-1',
      'chp' => '588.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '111555',
      'title' => 'Demon&#39;s Virtue',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '307.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '116709',
      'title' => 'END Initiated...',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '77.0',
      'frg' => '-1',
    ),
    4 => 
    array (
      'id' => '67860',
      'title' => 'I Reincarnated As A Stick',
      'availvol' => '-1',
      'availchp' => '81.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '193.0',
      'frg' => '-1',
    ),
    5 => 
    array (
      'id' => '112523',
      'title' => 'Is That A Wisp?',
      'availvol' => '-1',
      'availchp' => '98.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '535.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '90241',
      'title' => 'Mutagen',
      'availvol' => '-1',
      'availchp' => '131.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '550.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '119304',
      'title' => 'My cute (yandere) disciples&#39; side stories',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '9.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '100769',
      'title' => 'Nanomancer Reborn - I&#39;ve Become A Snow Girl?',
      'availvol' => '-1',
      'availchp' => '44.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '650.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '49528',
      'title' => 'Once Human, Now a Parasite',
      'availvol' => '32.0',
      'availchp' => '248.0',
      'availfrag' => '0.0',
      'vol' => '32.0',
      'chp' => '691.0',
      'frg' => '-1',
    ),
    10 => 
    array (
      'id' => '76584',
      'title' => 'Paragon of Destruction',
      'availvol' => '-1',
      'availchp' => '218.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '113019',
      'title' => 'Paragon of Sin',
      'availvol' => '-1',
      'availchp' => '3.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '116660',
      'title' => 'Project: Mage - The Frugal Mage',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '262.0',
      'frg' => '-1',
    ),
    13 => 
    array (
      'id' => '75505',
      'title' => 'Rise of Myriad Magic Emperor',
      'availvol' => '-1',
      'availchp' => '11.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '172.0',
      'frg' => '-1',
    ),
    14 => 
    array (
      'id' => '62773',
      'title' => 'Rise of the Undead Legion',
      'availvol' => '2.0',
      'availchp' => '22.0',
      'availfrag' => '0.0',
      'vol' => '2.0',
      'chp' => '488.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '105713',
      'title' => 'Sorceress 101',
      'availvol' => '-1',
      'availchp' => '31.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '361.0',
      'frg' => '-1',
    ),
    16 => 
    array (
      'id' => '111360',
      'title' => 'Supreme Lord Shapeshifter',
      'availvol' => '-1',
      'availchp' => '74.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '256.0',
      'frg' => '-1',
    ),
    17 => 
    array (
      'id' => '81839',
      'title' => 'Supreme Magus',
      'availvol' => '-1',
      'availchp' => '79.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '816.0',
      'frg' => '-1',
    ),
    18 => 
    array (
      'id' => '116659',
      'title' => 'Unfortunate Hero&#39;s Retirement Life',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    19 => 
    array (
      'id' => '117511',
      'title' => 'Venomancer Of Gaming',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    20 => 
    array (
      'id' => '119303',
      'title' => 'What do you mean my cute disciples are yanderes?',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '283.0',
      'frg' => '-1',
    ),
  ),
  'Qidian Plan To Read' => 
  array (
    0 => 
    array (
      'id' => '120307',
      'title' => 'A Bored Lich',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '117514',
      'title' => 'I&#39;ll Add Points To All Things',
      'availvol' => '-1',
      'availchp' => '39.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '117899',
      'title' => 'My Disciples Are All Villains',
      'availvol' => '-1',
      'availchp' => '37.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '96002',
      'title' => 'My female disciples are scary',
      'availvol' => '-1',
      'availchp' => '22.0',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '1.0',
      'frg' => '-1',
    ),
  ),
  'Reading' => 
  array (
    0 => 
    array (
      'id' => '32382',
      'title' => '100 Luck and the Dragon Tamer Skill!',
      'availvol' => '-1',
      'availchp' => '120.0',
      'availfrag' => '3.0',
      'vol' => '-1',
      'chp' => '38.0',
      'frg' => '-1',
    ),
    1 => 
    array (
      'id' => '57359',
      'title' => 'Age of Adepts',
      'availvol' => '-1',
      'availchp' => '1258.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '1050.0',
      'frg' => '-1',
    ),
    2 => 
    array (
      'id' => '32472',
      'title' => 'Blue Phoenix',
      'availvol' => '8.0',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1',
      'chp' => '198.0',
      'frg' => '-1',
    ),
    3 => 
    array (
      'id' => '49500',
      'title' => 'Eternal Souls',
      'availvol' => '-1',
      'availchp' => '7.0',
      'availfrag' => '-1',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    4 => 
    array (
      'id' => '49440',
      'title' => 'FOE Continent',
      'availvol' => '-1',
      'availchp' => '5.0',
      'availfrag' => '-1',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    5 => 
    array (
      'id' => '8458',
      'title' => 'Hardcore OP-ness',
      'availvol' => '2.0',
      'availchp' => '100.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '172.0',
      'frg' => '-1',
    ),
    6 => 
    array (
      'id' => '2461',
      'title' => 'I am a Slime',
      'availvol' => '-1',
      'availchp' => '1.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '4.0',
      'frg' => '-1',
    ),
    7 => 
    array (
      'id' => '32381',
      'title' => 'I was reincarnated as a Magic Academy!',
      'availvol' => '-1',
      'availchp' => '172.0',
      'availfrag' => '2.0',
      'vol' => '-1',
      'chp' => '86.0',
      'frg' => '-1',
    ),
    8 => 
    array (
      'id' => '111532',
      'title' => 'Inadvertently Invincible',
      'availvol' => '-1',
      'availchp' => '3633.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '30.0',
      'frg' => '-1',
    ),
    9 => 
    array (
      'id' => '42756',
      'title' => 'Lament of the Fallen',
      'availvol' => '-1',
      'availchp' => '204.0',
      'availfrag' => '0.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    10 => 
    array (
      'id' => '32080',
      'title' => 'Monster-less',
      'availvol' => '6.0',
      'availchp' => '4.0',
      'availfrag' => '0.0',
      'vol' => '6.0',
      'chp' => '4.0',
      'frg' => '-1',
    ),
    11 => 
    array (
      'id' => '668',
      'title' => 'Mushoku Tensei',
      'availvol' => '24.0',
      'availchp' => '261.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '214.0',
      'frg' => '-1',
    ),
    12 => 
    array (
      'id' => '43314',
      'title' => 'My Girlfriend is a Zombie',
      'availvol' => '-1',
      'availchp' => '414.0',
      'availfrag' => '2.0',
      'vol' => '-1',
      'chp' => '388.0',
      'frg' => '2.0',
    ),
    13 => 
    array (
      'id' => '49494',
      'title' => 'My wife, the Godlike Dungeon!',
      'availvol' => '-1',
      'availchp' => '4.0',
      'availfrag' => '-1',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    14 => 
    array (
      'id' => '142',
      'title' => 'Overlord',
      'availvol' => '14.0',
      'availchp' => '4.0',
      'availfrag' => '11.0',
      'vol' => '9.0',
      'chp' => '4.0',
      'frg' => '-1',
    ),
    15 => 
    array (
      'id' => '1789',
      'title' => 'Sate, Game Gardo wo Kouryaku Shiyouka.',
      'availvol' => '-1',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '-1.0',
      'chp' => '1.0',
      'frg' => '-1',
    ),
    16 => 
    array (
      'id' => '33444',
      'title' => 'Second Chance: a Wonderful New Life',
      'availvol' => '-1',
      'availchp' => '53.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '53.0',
      'frg' => '-1',
    ),
    17 => 
    array (
      'id' => '32444',
      'title' => 'Silver Death',
      'availvol' => '-1',
      'availchp' => '67.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '64.0',
      'frg' => '-1',
    ),
    18 => 
    array (
      'id' => '2801',
      'title' => 'Summoned Hero',
      'availvol' => '-1',
      'availchp' => '61.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '62.0',
      'frg' => '-1',
    ),
    19 => 
    array (
      'id' => '32713',
      'title' => 'Survival World RPG',
      'availvol' => '-1',
      'availchp' => '48.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '48.0',
      'frg' => '-1',
    ),
    20 => 
    array (
      'id' => '2051',
      'title' => 'Tate no Yuusha no Nariagari',
      'availvol' => '2.0',
      'availchp' => '-1',
      'availfrag' => '-1',
      'vol' => '9.0',
      'chp' => '378.0',
      'frg' => '-1',
    ),
    21 => 
    array (
      'id' => '34066',
      'title' => 'The Amber Sword',
      'availvol' => '3.0',
      'availchp' => '366.0',
      'availfrag' => '0.0',
      'vol' => '3.0',
      'chp' => '279.0',
      'frg' => '-1',
    ),
    22 => 
    array (
      'id' => '49508',
      'title' => 'The Blessing of 118 Gods',
      'availvol' => '2.0',
      'availchp' => '2.0',
      'availfrag' => '3.0',
      'vol' => NULL,
      'chp' => NULL,
      'frg' => NULL,
    ),
    23 => 
    array (
      'id' => '35771',
      'title' => 'The Empyrean Overlord',
      'availvol' => '-1',
      'availchp' => '52.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '52.0',
      'frg' => '-1',
    ),
    24 => 
    array (
      'id' => '34877',
      'title' => 'The Harem Was A Forced Goal',
      'availvol' => '2.0',
      'availchp' => '16.0',
      'availfrag' => '0.0',
      'vol' => '2.0',
      'chp' => '2.0',
      'frg' => '-1',
    ),
    25 => 
    array (
      'id' => '2487',
      'title' => 'The New Journey of an Old Soul',
      'availvol' => '-1',
      'availchp' => '107.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '99.0',
      'frg' => '-1',
    ),
    26 => 
    array (
      'id' => '33416',
      'title' => 'The New Start',
      'availvol' => '-1',
      'availchp' => '50.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '50.0',
      'frg' => '-1',
    ),
    27 => 
    array (
      'id' => '35213',
      'title' => 'The Once Simple Life of a Dungeon Skeleton',
      'availvol' => '1.0',
      'availchp' => '20.0',
      'availfrag' => '0.0',
      'vol' => '1.0',
      'chp' => '20.0',
      'frg' => '-1',
    ),
    28 => 
    array (
      'id' => '4168',
      'title' => 'The Overlord&#39;s Elite is now a Human?!',
      'availvol' => '-1',
      'availchp' => '37.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '37.0',
      'frg' => '-1',
    ),
    29 => 
    array (
      'id' => '2506',
      'title' => 'The Rude Time Stopper',
      'availvol' => '-1',
      'availchp' => '153.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '153.0',
      'frg' => '-1',
    ),
    30 => 
    array (
      'id' => '34067',
      'title' => 'The Strategy to Become Good at Magic',
      'availvol' => '-1',
      'availchp' => '110.0',
      'availfrag' => '0.0',
      'vol' => '-1',
      'chp' => '111.0',
      'frg' => '-1',
    ),
    31 => 
    array (
      'id' => '32486',
      'title' => 'The Strongest Magical Beast',
      'availvol' => '-1',
      'availchp' => '19.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '19.0',
      'frg' => '-1',
    ),
    32 => 
    array (
      'id' => '35460',
      'title' => 'The undead who yearned for life',
      'availvol' => '1.0',
      'availchp' => '37.0',
      'availfrag' => '0.0',
      'vol' => '1.0',
      'chp' => '37.0',
      'frg' => '-1',
    ),
    33 => 
    array (
      'id' => '34115',
      'title' => 'TMaster of Dungeon',
      'availvol' => '-1',
      'availchp' => '31.0',
      'availfrag' => '0.0',
      'vol' => '-1.0',
      'chp' => '31.0',
      'frg' => '-1',
    ),
  ),
);